### ISSUE TITLE
Opprett arrangement

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/issue-tracker#2]
Som arrangør 
ønsker jeg å opprette et arrangement
slik at jeg kan sende ut invitasjon

Arrangement bør ha følgende egenskaper:
- Dato
- Lokasjon
- Klasser
- Link til invitasjon
- Velkomsttekst
- (Konkurranseform (startordning, stilart, løypelengde)) - ikke med i MVP da en forenkling er at dette kan utledes fra deltakerlisten.

Arrangementet bør støttet reglementet til Skiforbundet.

**Comment by heming-langrenn** [comment]
Kodet ferdig og sjekket inn arrangement.
![events_screen](https://user-images.githubusercontent.com/56455987/123868862-8ea88b00-d930-11eb-9bc1-5b519f4fd252.png)
