### ISSUE TITLE
Bestemme rekkefølge av løpsklasser

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/issue-tracker#5]
Som arrangør
ønsker jeg å bestemme hvilken rekkefølge løpsklassene avvikles
slik at jeg kan generere kjøreplan

Må ta hensyn til
- hviletider for løpere,
- ulike løypetraseer

**Comment by heming-langrenn** [comment]
event-service-gui har nå mulighet til å redigere startrekkefølge på klassene.
