### ISSUE TITLE
Generere kjøreplan og startlister

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/issue-tracker#6]
Som arrangør
ønsker jeg å generere kjøreplan og startlister med ledige plasser for etteranmelding
slik at jeg kan publisere startlistene

**Comment by heming-langrenn** [comment]
Forslag til regelsett for fordeling av løpere til heat, A- og C- semifinaler og  A-, B- og C- finaler:

Deltakere | Heat | Regel | SA |   | SC |   | F
7 | 1 | Alle   til FA |   |   |   |   | 1
16 | 2 | 50%   FA, 50% FB | 0 |   | 0 |   | 2
24 | 3 | 40%   SA, 40% SB, resten FC | 2 | 4   FA, resten FB | 0 |   | 3
32 | 4 | 50%   SA, 50% SC | 2 | 4   FA, resten FB | 2 | 4   FC | 3
40 | 5 | 60%   SA, 40% SC | 3 | 3   FA, 3 FB | 2 | 4   FC | 3
48 | 6 | 50%   SA, 50% SC | 3 | 3   FA, 3 FB | 3 | 3   FC | 3
56 | 7 | 57%   SA, 43% SC | 4 | 2   FA, 2FB | 3 | 3   FC | 3
80 | 8 | 50%   SA, 50% SC | 4 | 2   FA, 2FB | 4 | 4   FC | 3
